name: AAA

on:
  workflow_dispatch:
 
permissions:
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Job 1
    container: php:8.5-cli-alpine
    steps:
      - name: Step 1
        run: |
          php -V
      
