name: AAA

on:
  #workflow_dispatch:
  push:
 
permissions:
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Job 1
    steps:
      - name: Step 1
        run: |
          echo "127.0.0.1 pebble" | sudo tee -a /etc/hosts
          echo "127.0.0.1 challtestsrv" | sudo tee -a /etc/hosts
          docker run --hostname pebble --rm -d -p 14000:14000 -p 15000:15000 ghcr.io/letsencrypt/pebble:latest
          docker run --hostname challtestsrv -p 5001:5001 -p 5002:5002 -p 5003:5003 -p 8053:8053 -p 8055:8055 -p 8443:8443 ghcr.io/letsencrypt/pebble-challtestsrv:latest


          
          
          wget --no-check-certificate https://127.0.0.1:14000/dir -O -
          
          php -v
      
