name: AAA

on:
  workflow_dispatch:
 
permissions:
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Job 1
    container: php:8.5-cli-alpine
    steps:
      - name: Step 1
        run: |
          apk add docker-cli
					docker run --rm -d -p 14000:14000 -p 15000:15000 ghcr.io/letsencrypt/pebble:latest
          php -v
      
