name: Run PHP HTTP test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: php:8.3-cli-alpine

    services:
      pebble:
        image: ghcr.io/letsencrypt/pebble:latest
        command: -strict
        ports:
          - 14000:14000 # HTTPS ACME API
      challtestsrv:
        image: ghcr.io/letsencrypt/pebble-challtestsrv:latest
        ports:
          - 8055:8055 # HTTP Management API
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Wait for foo
        run: |
          sleep 10

      - name: Run main.php :)
        run: php main.php